header: Services
subheader: We provide a wide range of 360 photo and video services.
items:
  - item:
    pict: fas fa-camera
    heading: Editing Panoramic 360° Photos
    descr: "Looking for an amazing 360° photo for a wedding anniversary, birthday, engagement party, or baby shower? Own a business and want to impress your clients with a 360° stitched panoramas that tells your story in a creative and unique format? Are you an artist, performer, or athlete who needs an exciting 360° photo to show off your talent? <br>I'm a 360° EDITOR who can create a panoramas that will rock your world! I use state-of-the-art technology, and I'm constantly upgrading my software/hardware and improving my techniques to ensure your viewers enjoy an engaging and professional 360° photo stitch.<br><br>
We doing:<br>
- Stitch and edit 360° panoramas<br>
- Add your logo, text at specified location<br>
- Ultra High Definition Quality<br>
- Remove Nadir<br>
- Provide 100% Satisfaction Guaranteed<br><br>

We work with GoPro, Nokia OZO, Ricoh Theta S, Xiaomi, 360fly, Kodak, Samsung GEAR 360 and more!"
  - item:
    pict: fas fa-globe
    heading: 360 Degree Panoramas With Your Drone
    descr: "Want a professional panorama shot on your DJI Mavic Pro? Or you have any other drone, just send me a shot of panormam and I stich it. I can sky feeling and on your panorama there will be no black hole in the zenith.<br><br>

I will:<br>
Stitch and edit 360° panoramas<br>
Sky feeling<br>
Add your logo, text at specified location<br>
Ultra High Definition Quality<br>
Provide 100% Satisfaction Guaranteed<br><br><br>

I work with all types of drones."
  - item:
    pict: fas fa-film
    heading: Editing 360 video
    descr: "
I'm a 360° VIDE0 EDITOR who can create a video that will rock your world! I use state-of-the-art technology, and I'm constantly upgrading my software/hardware and improving my techniques to ensure your viewers enjoy an engaging and professional 360° video stitch<br><br>

For the price, contact me. If the price is more than your budget we can agree.<br><br>

I use:<br>
- Autopano Video Pro (Kolor)<br>
- Giga<br>
- Nuke Cara VR<br>
- Adobe After Effects for post-production<br>
- Mocha VR for stabilization and rig removal<br><br>

I will:<br>
- Stitch and edit 360° video footage<br>
- optimize for 360° Facebook and YouTube<br>
- Color correction<br>
- 360° VFX<br>
- Add background music<br>
- Add your logo and text<br>
- 8K Ultra High Definition Quality<br>
- 360° titles<br>
- Remove Nadir<br>
- Stabilize the video<br>
- Provide 100% Satisfaction Guaranteed"
  - item:
    pict: fas fa-images
    heading: VR tours
    descr: "I will create premium quality virtual tours to increase your business!<br><br> 

Workflow:<br>
1. Contact us and brief us about your project<br>

2. Upload all files to our google drive that you want to integrate to your virtual tour<br>
- your 360° panorama images (we also can stitch them for you)<br>
- all other images<br>
- logo<br>
- information<br>
- video<br>
- music<br>

3. Custom offer: We charge you per Image, so you can easily control your budget.<br>

4. We start creating your amazing virtual tour<br><br>


Your benefits of our virtual tours:<br>
+ Increase your conversion rate up to 40%<br>
+ Virtual tours will keep people looking at your website 5 - 10 times longer <br>
+ virtual tour are twice as likely to generate interest of your business<br>
+ 360° photos gaining 45% more interaction<br>
+ Among 18-34-year-olds, prospects are 130% more likely to book a reservation or visit based on a virtual tour"
